# Generated by Django 5.0.3 on 2025-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CA', 'نقدي'), ('BN', 'تحويل بنكي'), ('CR', 'بطاقة'), ('CH', 'شيك')], default=0, max_length=2, verbose_name='طريقة الدفع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='إيصال الدفع'),
        ),
    ]
