# Generated by Django 5.0.3 on 2025-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_remove_payment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='المبلغ (ر.ع)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name='تاريخ الدفع'),
        ),
    ]
