# Generated by Django 5.2.1 on 2025-05-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessor_name', models.CharField(max_length=255, verbose_name='اسم المؤجر')),
                ('lessor_type', models.CharField(choices=[('AG', 'اتفاقة/شراكة'), ('CR', 'سجل تجاري'), ('CV', 'شخص'), ('EM', 'سفارة'), ('FC', 'شركة أجنبية'), ('GV', 'جهة حكومة'), ('HT', 'ورثة'), ('PR', 'سجل مهني')], max_length=3, verbose_name='نوع المؤجر')),
                ('lessor_relation', models.CharField(choices=[('INV', 'مستثمر'), ('BEN', 'منتفع')], max_length=3, verbose_name='علاقة المؤجر')),
                ('is_lessor_owner_of_building', models.BooleanField(verbose_name='هل المؤجر هو مالك المبنى؟')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('purpose_of_contract', models.CharField(choices=[('REINV', 'استثمار لإعادة التأجير'), ('COM', 'تجاري'), ('RES', 'سكني'), ('IND', 'صناعي')], max_length=10, verbose_name='الغرض من العقد')),
                ('residential_usage', models.CharField(choices=[('LF', 'سكن قوى عاملة - عائلي'), ('LS', 'سكن قوى عاملة - عزابي'), ('FAM', 'سكن عائلي'), ('SIN', 'سكن عزابي'), ('STU', 'سكن طلاب'), ('FSTU', 'سكن طالبات')], max_length=4, verbose_name='نوع السكن')),
                ('land_usage_puropose', models.CharField(choices=[('AGR', 'زراعي'), ('COM', 'تجاري'), ('GOV', 'حكومي'), ('IND', 'صناعي'), ('RES', 'سكني'), ('MIX', 'سكني تجاري')], max_length=4, verbose_name='الغرض من استعمال الأرض')),
                ('rent_amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='قيمة الإيجار')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='المستأجر')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-created_at'],
            },
        ),
    ]
