# Generated by Django 5.0.2 on 2025-06-24 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء العقد')),
                ('monthly_rent', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الإيجار الشهري (ريال عماني)')),
                ('security_deposit', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='التأمين (ريال عماني)')),
                ('admin_fees', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الرسوم الإدارية (ريال عماني)')),
                ('office_fees', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='رسوم المكتب (ريال عماني)')),
                ('additional_fees', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='رسوم إضافية (ريال عماني)')),
                ('total_fees', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='إجمالي الرسوم (ريال عماني)')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expiring_soon', 'قريب من الانتهاء'), ('expired', 'منتهي'), ('cancelled', 'ملغي'), ('renewed', 'مجدد')], default='active', max_length=20, verbose_name='حالة العقد')),
                ('terms_and_conditions', models.TextField(verbose_name='الشروط والأحكام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الإيجار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateField(verbose_name='تاريخ الإلغاء')),
                ('reason', models.TextField(verbose_name='سبب الإلغاء')),
                ('owner_signature', models.BooleanField(default=False, verbose_name='توقيع المالك')),
                ('tenant_signature', models.BooleanField(default=False, verbose_name='توقيع المستأجر')),
                ('legal_responsibility_accepted', models.BooleanField(default=False, verbose_name='قبول المسؤولية القانونية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إلغاء عقد',
                'verbose_name_plural': 'إلغاءات العقود',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'عقد إيجار'), ('cancellation', 'إلغاء عقد'), ('renewal', 'تجديد عقد'), ('commitment', 'تعهد سداد'), ('civil_id', 'هوية مدنية'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستند')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='documents/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('rent', 'إيجار'), ('deposit', 'تأمين'), ('fees', 'رسوم'), ('utilities', 'مرافق')], max_length=20, verbose_name='نوع الدفع')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='المبلغ (ريال عماني)')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الدفعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='UtilityCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_commitment', models.BooleanField(default=True, verbose_name='تعهد سداد الكهرباء')),
                ('water_commitment', models.BooleanField(default=True, verbose_name='تعهد سداد الماء')),
                ('other_utilities', models.TextField(blank=True, verbose_name='مرافق أخرى')),
                ('tenant_signature', models.BooleanField(default=False, verbose_name='توقيع المستأجر')),
                ('signature_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تعهد سداد مرافق',
                'verbose_name_plural': 'تعهدات سداد المرافق',
            },
        ),
    ]
