# Generated by Django 5.0.3 on 2025-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'عقد', 'verbose_name_plural': 'العقود'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_lessor_owner_of_building',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='land_usage_puropose',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lessor_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lessor_relation',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lessor_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='purpose_of_contract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='residential_usage',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='ملف العقد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('AC', 'ساري'), ('EN', 'منتهي'), ('CA', 'ملغي')], default='AC', max_length=2, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rent_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الإيجار الشهري'),
        ),
    ]
