# Generated by Django 5.0.2 on 2025-06-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('properties', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.owner', verbose_name='المالك'),
        ),
        migrations.AddField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='العقار'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant', verbose_name='المستأجر'),
        ),
        migrations.AddField(
            model_name='contractcancellation',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='document',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='utilitycommitment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='العقد'),
        ),
    ]
