# Generated by Django 5.0.3 on 2025-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_options_remove_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'عقد إيجار', 'verbose_name_plural': 'عقود الإيجار'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='rent_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الإيجار الشهري (ر.ع)'),
        ),
    ]
