# Generated by Django 5.0.3 on 2025-05-17 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_options_alter_contract_rent_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date'], 'verbose_name': 'عقد إيجار', 'verbose_name_plural': 'عقود الإيجار'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='النشاط التجاري'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
