# Generated by Django 5.0.3 on 2025-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tenant',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='tenants_ids/', verbose_name='صورة الهوية'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('AC', 'نشط'), ('LF', 'منسحب'), ('LT', 'متأخر')], default='AC', max_length=2, verbose_name='الحالة'),
        ),
    ]
