# Generated by Django 5.0.3 on 2025-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_created_at_remove_tenant_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('AC', 'نشط'), ('LF', 'منسحب'), ('LT', 'متأخر عن السداد')], default='AC', max_length=2, verbose_name='الحالة'),
        ),
    ]
