# Generated by Django 5.0.2 on 2025-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('office', 'مكتب'), ('shop', 'محل تجاري'), ('warehouse', 'مستودع')], max_length=20, verbose_name='نوع العقار')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العقار')),
                ('description', models.TextField(verbose_name='وصف العقار')),
                ('area', models.CharField(max_length=100, verbose_name='المنطقة')),
                ('street', models.CharField(max_length=100, verbose_name='الشارع')),
                ('building_number', models.CharField(max_length=20, verbose_name='رقم المبنى')),
                ('floor_number', models.CharField(max_length=10, verbose_name='رقم الطابق')),
                ('apartment_number', models.CharField(max_length=10, verbose_name='رقم الشقة')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='عدد الغرف النوم')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='عدد دورات المياه')),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المساحة (متر مربع)')),
                ('monthly_rent', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الإيجار الشهري (ريال عماني)')),
                ('security_deposit', models.DecimalField(decimal_places=3, max_digits=10, verbose_name=' التأمين (ريال عماني)')),
                ('has_parking', models.BooleanField(default=False, verbose_name='موقف سيارات')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='مصعد')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='شرفة')),
                ('has_garden', models.BooleanField(default=False, verbose_name='حديقة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح للإيجار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور العقارات',
            },
        ),
    ]
