# Generated by Django 5.2.1 on 2025-05-08 20:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المبنى')),
                ('building_type', models.CharField(choices=[('RESIDENTIAL', 'سكني'), ('COMMERCIAL', 'تجاري'), ('MIXED', 'مختلط'), ('GOVERNMENTAL', 'حكومي')], max_length=20, verbose_name='نوع المبنى')),
                ('address', models.TextField(verbose_name='العنوان التفصيلي')),
                ('location_link', models.URLField(blank=True, verbose_name='رابط الموقع على خرائط Google')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المالك')),
                ('owner_phone', models.CharField(blank=True, max_length=15, verbose_name='رقم هاتف المالك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'مباني',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='المحافظة')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='الكود')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'محافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم الطابق')),
                ('description', models.TextField(verbose_name='وصف الطابق')),
                ('floor_plan', models.ImageField(blank=True, upload_to='floor_plans/', verbose_name='خريطة الطابق')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'طابق',
                'verbose_name_plural': 'طوابق',
                'ordering': ['building', 'number'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='governorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buildings.governorate', verbose_name='المحافظة'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, verbose_name='رقم الوحدة')),
                ('unit_type', models.CharField(choices=[('APARTMENT', 'شقة'), ('OFFICE', 'مكتب'), ('SHOP', 'محل تجاري'), ('VILLA', 'فيلا'), ('HALL', 'قاعة')], max_length=20, verbose_name='نوع الوحدة')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المساحة (م2)')),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإيجار الشهري (ر.ع.)')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة للتأجير')),
                ('features', models.JSONField(default=dict, verbose_name='المميزات')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.floor', verbose_name='الطابق')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'وحدات',
                'ordering': ['floor__building', 'floor__number', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Wilayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الولاية')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='الكود')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildings.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'ولاية',
                'verbose_name_plural': 'ولايات',
                'ordering': ['governorate__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='wilayat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buildings.wilayat', verbose_name='الولاية'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 0)), name='floor_number_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'number')},
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('floor', 'unit_number'), name='unique_unit_per_floor'),
        ),
        migrations.AddConstraint(
            model_name='wilayat',
            constraint=models.UniqueConstraint(fields=('governorate', 'name'), name='unique_wilayat'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['name'], name='buildings_b_name_7f3d06_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['building_type'], name='buildings_b_buildin_66da13_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['governorate', 'wilayat'], name='buildings_b_governo_2ce250_idx'),
        ),
    ]
