# Generated by Django 5.2.1 on 2025-05-08 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المبنى')),
                ('building_type', models.CharField(choices=[('RESIDENTIAL', 'سكني'), ('COMMERCIAL', 'تجاري'), ('MIXED', 'مختلط')], max_length=20, verbose_name='نوع المبنى')),
                ('address', models.TextField(verbose_name='العنوان التفصيلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'مباني',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='المحافظة')),
                ('code', models.CharField(max_length=2, verbose_name='الكود')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'محافظات',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم الطابق')),
                ('description', models.TextField(verbose_name='وصف الطابق')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'طابق',
                'verbose_name_plural': 'طوابق',
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.AddField(
            model_name='building',
            name='governorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.governorate', verbose_name='المحافظة'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, verbose_name='رقم الوحدة')),
                ('unit_type', models.CharField(choices=[('APARTMENT', 'شقة'), ('OFFICE', 'مكتب'), ('SHOP', 'محل'), ('VILLA', 'فيلا')], max_length=20, verbose_name='نوع الوحدة')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المساحة (م2)')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة للتأجير')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.floor', verbose_name='الطابق')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'وحدات',
                'ordering': ['floor__building', 'floor__number', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Wilayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الولاية')),
                ('code', models.CharField(max_length=2, verbose_name='الكود')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'ولاية',
                'verbose_name_plural': 'ولايات',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='wilayat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.wilayat', verbose_name='الولاية'),
        ),
    ]
