# Generated by Django 5.2.1 on 2025-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوحدة')),
                ('floor', models.IntegerField(verbose_name='الطابق')),
                ('building_name', models.CharField(max_length=255, verbose_name='اسم المبنى')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='مشغولة؟')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
            },
        ),
    ]
