# Generated by Django 5.0.3 on 2025-05-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governorate',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='wilayat',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='الكود'),
        ),
    ]
