# Generated by Django 5.2.1 on 2025-05-08 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governorate',
            options={'ordering': ['name'], 'verbose_name': 'محافظة', 'verbose_name_plural': 'محافظات'},
        ),
        migrations.AlterModelOptions(
            name='wilayat',
            options={'ordering': ['governorate__name', 'name'], 'verbose_name': 'ولاية', 'verbose_name_plural': 'ولايات'},
        ),
        migrations.AddField(
            model_name='building',
            name='location_link',
            field=models.URLField(blank=True, verbose_name='رابط الموقع على خرائط Google'),
        ),
        migrations.AddField(
            model_name='building',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم المالك'),
        ),
        migrations.AddField(
            model_name='building',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم هاتف المالك'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_plan',
            field=models.ImageField(blank=True, upload_to='floor_plans/', verbose_name='خريطة الطابق'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='features',
            field=models.JSONField(default=dict, verbose_name='المميزات'),
        ),
        migrations.AddField(
            model_name='unit',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإيجار الشهري (ر.ع.)'),
        ),
        migrations.AddField(
            model_name='wilayat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AddField(
            model_name='wilayat',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'سكني'), ('COMMERCIAL', 'تجاري'), ('MIXED', 'مختلط'), ('GOVERNMENTAL', 'حكومي')], max_length=20, verbose_name='نوع المبنى'),
        ),
        migrations.AlterField(
            model_name='building',
            name='governorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buildings.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='building',
            name='wilayat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='buildings.wilayat', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المساحة (م2)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('APARTMENT', 'شقة'), ('OFFICE', 'مكتب'), ('SHOP', 'محل تجاري'), ('VILLA', 'فيلا'), ('HALL', 'قاعة')], max_length=20, verbose_name='نوع الوحدة'),
        ),
        migrations.AlterField(
            model_name='wilayat',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='wilayat',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildings.governorate', verbose_name='المحافظة'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['name'], name='buildings_b_name_7f3d06_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['building_type'], name='buildings_b_buildin_66da13_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['governorate', 'wilayat'], name='buildings_b_governo_2ce250_idx'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 0)), name='floor_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('floor', 'unit_number'), name='unique_unit_per_floor'),
        ),
        migrations.AddConstraint(
            model_name='wilayat',
            constraint=models.UniqueConstraint(fields=('governorate', 'name'), name='unique_wilayat'),
        ),
    ]
