# Generated by Django 5.0.3 on 2025-05-14 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='المساحة (م2)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الإحداثيات'),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_furnished',
            field=models.BooleanField(default=False, verbose_name='مؤثثة؟'),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('AP', 'شقة'), ('VI', 'فيلا'), ('SH', 'محل'), ('BLB', 'لوحة اعلانية'), ('OFF', 'مكتب'), ('MAL', 'مول')], default=django.utils.timezone.now, max_length=4, verbose_name='نوع الوحدة'),
            preserve_default=False,
        ),
    ]
