# Generated by Django 5.0.3 on 2025-05-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_unit_area_unit_coordinates_unit_is_furnished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='المساحة (م2)'),
        ),
    ]
