# Generated by Django 5.0.3 on 2025-05-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_governorate_code_alter_wilayat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilayat',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='الكود'),
        ),
    ]
