# Generated by Django 5.0.3 on 2025-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_unit_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'وحدة عقارية', 'verbose_name_plural': 'الوحدات العقارية'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='building_name',
            field=models.CharField(max_length=255, verbose_name='اسم البناية'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.IntegerField(verbose_name='رقم الطابق'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_furnished',
            field=models.BooleanField(default=False, verbose_name='هل مؤثثة؟'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='هل الوحدة مشغولة؟'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('AP', 'شقة'), ('VI', 'فيلا'), ('SH', 'محل تجاري'), ('OFF', 'مكتب'), ('WRH', 'مخزن')], max_length=4, verbose_name='نوع الوحدة'),
        ),
    ]
